### ISSUE TITLE
ICompletionParticipant#onXMLContent is not called for CDATA

### ISSUE THREAD

**Issue by laeubi** [eclipse-lemminx/lemminx#1694]
Assume the following XML fragment:

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>test</groupId>
	<artifactId>bnd-integration-test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>BND-M2E Integration Test Project</name>
	<description>This project test the BND-m2e integration</description>
	<build>
		<plugins>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-maven-plugin</artifactId>
				<version>7.0.0</version>
				<executions>
					<execution>
						<id>bnd-process</id>
						<goals>
							<goal>bnd-process</goal>
						</goals>
						<configuration>
						<bnd>
						
						<![CDATA[ 
						  
						]]>
						</bnd>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.core</artifactId>
			<version>8.0.0</version>
		</dependency>
	</dependencies>
</project>
```

if I place the cursor right after `<bnd>` (before the CDATA section) then `ICompletionParticipant#onXMLContent` is called with `currentTag=bnd`

Now place the cursor inside the 
```
<![CDATA[ 					  

]]>
```

now `onXMLContent` is not called. As CDATA only marks some parts of the document to contain any chardata it is still XML Content of the element, so I would have expected that the method is still called (maybe with currentTag=CDATA and parentTag=bnd).

**Comment by angelozerr** [comment]
As we have no usecases with cdata completion , lemminx doent support that.

If yiu need to support cdata completion, any contribution are welcome!

**Comment by laeubi** [comment]
> As we have no usecases with cdata completion , lemminx doent support that.

As `CDATA` can appear anywhere in a document / element content I'm not sure I understand why "non cdata" sections should be any different usecases?

e.g. 

```
<dependencies>
	<dependency>
		<groupId>org.osgi</groupId>
		<artifactId>osgi.core</artifactId>
		<version><![CDATA[8.0.0]]></version>
	</dependency>
</dependencies
```

is valid XML (even though unusual) where lemminx-maven would usually provide a completion for the version number (wich won't work also).

**Comment by laeubi** [comment]
> > the CDATA section seem to be recognized correctly as a text node child.
> 
> Indeed the xml parser convers that. You just need to use those information to support onCDATA with participant

I'll try to take a look but as I'm not familiar with lemminx internals the "just" might become a more complicated (for me) ;-)

**Comment by angelozerr** [comment]
I.will do my best to help you.

**Comment by laeubi** [comment]
I debugged a little bit and found that the tokentype is `CDATATagOpen` at this point and `org.eclipse.lemminx.services.XMLCompletions.doComplete(DOMDocument, Position, SharedSettings, CancelChecker)` just fall into the default case then, then next token is of type `CDATAContent` ... so from code point of view (was not able to test yet) the case 

`case Content:`

should actually be 

```
case Content:
case CDATAContent:
```

could probably already fix the issue...

**Comment by angelozerr** [comment]
We have a lot of tests, so dont be shy to break anything and we will see if it breaks existing tests.

**Comment by laeubi** [comment]
I now started with a first step by creating a testcase, it seems there is no "basic" test for the XML extension ("only" HTML variant) so I created a dedicated new test:
- https://github.com/eclipse-lemminx/lemminx/pull/1699

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse-lemminx/lemminx/pull/1699

**Comment by laeubi** [comment]
Thanks! After some struggling around I was able to finally test this:

https://github.com/user-attachments/assets/9b4d87c3-c42a-476e-9b97-b102df4db42b

so it works like expected!

Sadly it seem to mean that:

1. We need a new lemminx release
2. then need to update wildwebdevelopers
3. then need a new wildwebdevelopers release

so a quite long path from now on until its fully available. May I ask if there is any plans for new lemminx release already?

**Comment by angelozerr** [comment]
I think we can create a release of LemMinx but I don't know. We need to find time to do that.
