### ISSUE TITLE
Don't log to System.err/out

### ISSUE THREAD

**Issue by fbricon** [eclipse-lemminx/lemminx#19]
... or call exception.printStackTrace();

stdio is used to exchange messages with the client. Logging to standard streams will break the client/server communication.

Either log messages via a logging facade (slf4j?) to a log file, and/or log messages to the client

**Comment by angelozerr** [comment]
Totally agree with you @fbricon! IMHO I think we should use an existing logger API like:

 * http://www.vogella.com/tutorials/Logging/article.html which doesn't require some dependencies
 * sl4j which requires a new dependencies.

Perhaps http://www.vogella.com/tutorials/Logging/article.html  is enough for lsp4xml case?

**Comment by angelozerr** [comment]
Guys, your idea with config file to customize log (client, file, etc) looks very promising. Once you will implement it, please update the wiki https://github.com/angelozerr/lsp4xml/wiki/Configuration#logging that I have initialized. Thanks!
