### ISSUE TITLE
Basic XML validation for no well XML

### ISSUE THREAD

**Issue by angelozerr** [eclipse-lemminx/lemminx#34]
I don't know if it's an hard task, but I tell me if we could use our XML scanner to validate XML files for no well XML (XML which doesn't end an element tag, etc).

Today, I'm using Xerces to do that, but the main problem is that SAXParserException contains only a start line/character and not the end. 

I have studied WTP XML validator and they do like this:

 * validate XML file with their internal DOM (structured region) https://github.com/eclipse/webtools.sourceediting/blob/master/xml/bundles/org.eclipse.wst.xml.core/src-validation/org/eclipse/wst/xml/core/internal/validation/MarkupValidator.java -> it looks like of our XMLDocument

 * validate XML file with their internal Token https://github.com/eclipse/webtools.sourceediting/blob/master/xml/bundles/org.eclipse.wst.xml.core/src-validation/org/eclipse/wst/xml/core/internal/validation/StreamingMarkupValidator.java -> it looks like of our XML Scanner.

The benefit to do that is that you can highlight the element tag when there is an error.

For the XML Schema error, WTP adjust the start/end location according error message like https://github.com/microclimate-devops/xml-language-server does too.

I would like to follow the same idea than WTP/XML Editor:

 * manage basic XML validation with our XML Scanner tokens. This feature will be managed in the core.
 * manage validation based on XML Schema, DTD, etc with Xerces. Those features will be move to contentmodel extension project.

IMHO, if we can do that, we will have a clean validation mean and it will be easy to extend too validation to valiudate other things (ex: validate java class defines in @class attribute, etc)

@fbricon @NikolasKomonen what do you think about that?

**Comment by NikolasKomonen** [comment]
This is a good idea, just to be sure would you want to modify the XMLScanner to also do basic validation and take over the responsibility of XMLDiagnostics?

**Comment by angelozerr** [comment]
> you want to modify the XMLScanner

no just use it.

**Comment by NikolasKomonen** [comment]
@angelozerr are you already working on implementing the XMLScanner to report errors?

**Comment by angelozerr** [comment]
> @angelozerr are you already working on implementing the XMLScanner to report errors?

No, but my idea is to loop for XMLScanner tokens and check if token is a good token (ex : after start tag element, you need a tag element, etc) like https://github.com/eclipse/webtools.sourceediting/blob/master/xml/bundles/org.eclipse.wst.xml.core/src-validation/org/eclipse/wst/xml/core/internal/validation/StreamingMarkupValidator.java seems doing.

Do you want work on this issue?

**Comment by NikolasKomonen** [comment]
@angelozerr yeah, is that fine?

**Comment by NikolasKomonen** [comment]
@angelozerr Hi, I found that with the current implementation of the XMLParser and XMLScanner certain cases eg:

 `<tag key="value" </tag>`

would not recognise the start tag as incomplete while other IDE's like intellij do.

Right now the XMLScanner will continue reading until it hits the '>' of the end tag. I'm planning on modifying the Scanner to consider this case and possibly other cases I find, so that not well-formed documents are better handled. 

Do you see any issues with this?

**Comment by angelozerr** [comment]
> I'm planning on modifying the Scanner to consider this case and possibly other cases I find, so that not well-formed documents are better handled.

> Implementing this should also help for better diagnostics since more accurate tokens will be given.

Great!

> Do you see any issues with this?

Today the scanner behaviour is the  same than vscode html language service. So I was confident. 

To be honnest with you, I'm a little scare to change it because scanner is used a lot (in completion, etc), but as we have several JUnit I think you can try to refactor it. But please add the more JUnit that you can write.

**Comment by NikolasKomonen** [comment]
You are right, it does effect some other parts (In parser, but I fixed it).
I'll experiment and see how much it disturbs other parts of the code.

**Comment by angelozerr** [comment]
@NikolasKomonen I have not finished my work, but it starts working well. The last part is to adjust range position from the SAX error, because it gives you just one offset (not start/end offset).

I have started to implement that at https://github.com/angelozerr/lsp4xml/blob/master/extensions/org.eclipse.lsp4xml.contentmodel/src/main/java/org/eclipse/lsp4xml/contentmodel/participants/diagnostics/LSPErrorReporter.java#L119 and write tests at https://github.com/angelozerr/lsp4xml/blob/master/extensions/org.eclipse.lsp4xml.contentmodel/src/test/java/org/eclipse/lsp4xml/contentmodel/xsd/XMLBasicDiagnosticsTest.java

We need to write tests for the whole code https://wiki.xmldation.com/Support/Validator

If you wish to help me with that, please tell me in order to we share the error code.

Please give me feedback.

**Comment by angelozerr** [comment]
Here a sample of adjust that I have managed:

![image](https://user-images.githubusercontent.com/1932211/44087303-b36730e8-9fbf-11e8-9cca-419442a19137.png)

You can see that the whole tag name is highlighted and not just one character.

**Comment by NikolasKomonen** [comment]
@angelozerr I've been working on the basic validation, will you new Validation be replacing this? Also I'll start working on tests for the link you gave.

**Comment by angelozerr** [comment]
> @angelozerr I've been working on the basic validation, 

Great!

> will your new Validation be replacing this? Also I'll start working on tests for the link you gave.

I think we can have the same result than your work but I'm not sure about performance?

**Comment by NikolasKomonen** [comment]
@angelozerr How did you configure you extension diagnostics, doExtensionsDiagnostics() is being called in doDiagnostics() but extensionsRegistry.getDiagnosticsParticipants() is returning an empty list

**Comment by angelozerr** [comment]
With SPI in https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/services/extensions/XMLExtensionsRegistry.java#L70 by using  https://github.com/angelozerr/lsp4xml/tree/master/extensions/org.eclipse.lsp4xml.contentmodel/src/main/resources/META-INF/services which must be in your classpath (your JAR). Please note that the all JAR doesn't contains extension (perhaps it's your problem?).
